RubiconDeFi/docs

src/components/Layout.jsx

hide for now, waiting for approval

ripped out search

---

src/pages/docs/protocol/deployments.md
yarn.lock

updated to link to most up-to-date market-aid address on goerli

patch: updated goerli factory link

---

src/components/Layout.jsx
src/pages/docs/protocol/mainnet_deployments.md
src/pages/docs/protocol/testnet_deployments.md

Note that I just kept our current one as "v1 Deployment" and added a Mainnet Deployments and Testnet Deployments tables

New Mainnet Deployments and Testnet Deployments pages

---

components/Callout.jsx
pages/faq.en.mdx
pages/faq.mdx
pages/index.en.mdx
pages/protocol/_meta.en.json
pages/protocol/_meta.json
pages/protocol/deployments.en.mdx
pages/protocol/deployments.mdx
pages/protocol/risks.en.mdx
pages/protocol/risks.mdx
pages/protocol/rubicon-market/batch-orders.en.mdx
pages/protocol/rubicon-market/contract-overview.en.mdx
pages/protocol/rubicon-market/contract-overview.mdx
pages/protocol/rubicon-market/fees.en.mdx
pages/protocol/rubicon-market/fees.mdx
pages/protocol/rubicon-market/market-aid.en.mdx
pages/protocol/rubicon-router/rubicon-router.en.mdx
theme.config.jsx

This PR contains comprehensive updates to the docs for the launch of Rubicon V2 contracts.
This includes updates to functions, contract overviews, deployments, fees, and users guides.
DO NOT MERGE unless V2 contracts are live.

V2 Mainnet Updates

---

pages/protocol/rubicon-market/batch-orders.en.mdx
pages/protocol/rubicon-market/contract-overview.en.mdx
pages/protocol/rubicon-router/rubicon-router.en.mdx

Removes outdated code in some functions.

Cleanup: remove excess and outdated code from functions

---

components/ThemeSelector.jsx
theme.config.jsx

Default to dark mode and add searchbar default text

---

pages/protocol/rubicon-market/min-order-sizes.en.mdx
pages/protocol/rubicon-market/min-order-sizes.mdx

Hotfix for Min Order Sizes metadata

---

pages/protocol/deployments.en.mdx
pages/protocol/deployments.mdx

closes #30 - corrects docs addresses

fix: arbitrum goerli addresses #30

---

pages/protocol/deployments.en.mdx
pages/protocol/deployments.mdx

Fixes OP Goerli Router contract address

---

pages/faq.mdx
pages/index.en.mdx
pages/index.mdx

after initial overview, give a deeper breakdown of what rubicon is and aims to be 🌏📖

update: Protocol Overview

---

pages/market-making/market-making-overview.en.mdx
pages/market-making/market-making-overview.mdx
pages/protocol/rubicon-market/fees.en.mdx
pages/protocol/rubicon-market/fees.mdx

Update Maker Fee

---

pages/protocol/rubicon-v4/fees.en.mdx

fix: typo, indentation

---

pages/faq.en.mdx

fix: markdown typo

---

pages/_meta.en.json
pages/rubiconLiquidityProgram.en.mdx

A program to reward liquidity providers

Add Rubicon Liquidity Program

---

pages/rubiconRfq.en.mdx

- Update response schemas for `/price-levels` and `/*match` endpoints.
- Add description for a new `/market-match` endpoint.
- Add description for `WebSocket` connection with the server.
- New `RubiconRFQ` contract addresses.

feat: update `RubiconRFQ` docs

---

pages/rubiconRfq.en.mdx

fix: wrong topic's number

---

pages/rubiconRfq.en.mdx

feat: yet another new field in the response

---

pages/api-guides/rubicon-classic/subgraphs/subgraphs.en.mdx

1. `Optimism mainnet` subgraph updated
2. `Base mainnet` subgraph added.

feat: update subgraphs

---

components/Layout.jsx
pages/opLiquidityRewards.en.mdx

New liquidity rewards approach

---

next.config.js
pages/_meta.json
pages/rubi/_meta.json
pages/rubi/deployments.mdx
pages/rubi/incentives.mdx
pages/rubi/overview.mdx
pages/rubi/tokenomics.mdx

- Removes outdated `sidebar` from `next.config.js`.
- Syncs `pages/_meta.json` with `pages/_meta.en.json`

fix: sidebar structure
